#!/bin/bash

# shellcheck disable=SC1090
. "$(dirname "$0")/alltags.sh"

IMG=$(basename "$DOCKER_REPO")
for tag in $(alltags "$IMG"|inverse); do
    echo "======================= Building ${IMG}:$tag"
    if echo "$tag" | grep -qo alpine; then
        docker build --build-arg SRCTAG="$tag" -t "${DOCKER_REPO}:$tag" -f Dockerfile.alpine .
    else
        docker build --build-arg SRCTAG="$tag" -t "${DOCKER_REPO}:$tag" .
    fi
done
