#!/bin/bash

# shellcheck disable=SC1090
. "$(dirname "$0")/reg-tags/image_tags.sh"

token=$(img_auth "$DOCKER_REPO")
for tag in $(img_tags --filter '^[0-9]+(\.[0-9]+)+(-alpine[0-9]+(\.[0-9]+)+)?$' --verbose -- "$(basename "$DOCKER_REPO")"); do
    revision=$(img_labels --verbose --token "$token" -- "$DOCKER_REPO" "$tag" |
                grep "^org.opencontainers.image.revision" |
                sed -E 's/^org.opencontainers.image.revision=(.+)/\1/')
    if [ "$revision" != "$SOURCE_COMMIT" ]; then
        echo "============== No ${DOCKER_REPO}:$tag at $SOURCE_COMMIT"
        docker build \
            --build-arg SRCTAG="$tag" \
            --tag "${DOCKER_REPO}:$tag" \
            --label "org.opencontainers.image.revision=$SOURCE_COMMIT" \
            .
    fi
done
